ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'RESPOND';
ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'CREATE_MEMORY';
ALTER TYPE "AiActionType" ADD VALUE IF NOT EXISTS 'UPDATE_RELATIONSHIP';
