const NATIONALITY_PT_BR: Record<string, string> = {
  british: "Britânico",
  english: "Inglês",
  scottish: "Escocês",
  welsh: "Galês",
  dutch: "Neerlandês",
  netherlandish: "Neerlandês",
  thai: "Tailandês",
  spanish: "Espanhol",
  italian: "Italiano",
  french: "Francês",
  german: "Alemão",
  australian: "Australiano",
  canadian: "Canadense",
  portuguese: "Português",
  brazilian: "Brasileiro",
  mexican: "Mexicano",
  finnish: "Finlandês",
  monegasque: "Monegasco",
  monégasque: "Monegasco",
  japanese: "Japonês",
  danish: "Dinamarquês",
  swedish: "Sueco",
  austrian: "Austríaco",
  belgian: "Belga",
  swiss: "Suíço",
  argentine: "Argentino",
  argentinian: "Argentino",
  "new zealander": "Neozelandês",
  "south african": "Sul-africano",
  russian: "Russo",
  polish: "Polonês",
  chinese: "Chinês",
  american: "Americano",
  indonesian: "Indonésio",
  irish: "Irlandês",
  colombian: "Colombiano",
  venezuelan: "Venezuelano",
  indian: "Indiano",
  malaysian: "Malaio",
  hungarian: "Húngaro",
  czech: "Tcheco",
  slovak: "Eslovaco",
  estonian: "Estoniano",
  latvian: "Letão",
  lithuanian: "Lituano",
  emirati: "Emiradense",
  saudi: "Saudita",
  bahraini: "Barenita",
  kuwaiti: "Kuwaitiano",
  qatari: "Catariano",
  turkish: "Turco",
  greek: "Grego",
  romanian: "Romeno",
  bulgarian: "Búlgaro",
  croatian: "Croata",
  serbian: "Sérvio",
  slovenian: "Esloveno",
  norwegian: "Norueguês",
  icelandic: "Islandês",
  israeli: "Israelense",
  lebanese: "Libanês",
  egyptian: "Egípcio",
  moroccan: "Marroquino",
  chilean: "Chileno",
  uruguayan: "Uruguaio",
  paraguayan: "Paraguaio",
  peruvian: "Peruano",
  ecuadorian: "Equatoriano",
  bolivian: "Boliviano",
  venezuelian: "Venezuelano",
  korean: "Coreano",
  "south korean": "Sul-coreano",
  singaporean: "Singapurense",
  "hong konger": "Hongkonguês",
  taiwanese: "Taiwanês",
  philippine: "Filipino",
  filipino: "Filipino",
  vietnamese: "Vietnamita",
  nigerian: "Nigeriano",
  kenyan: "Queniano",
  ghanaian: "Ganês",

  gbr: "Britânico",
  ned: "Neerlandês",
  tha: "Tailandês",
  esp: "Espanhol",
  ita: "Italiano",
  fra: "Francês",
  ger: "Alemão",
  deu: "Alemão",
  aus: "Australiano",
  can: "Canadense",
  por: "Português",
  bra: "Brasileiro",
  mex: "Mexicano",
  fin: "Finlandês",
  mon: "Monegasco",
  jpn: "Japonês",
  den: "Dinamarquês",
  swe: "Sueco",
  aut: "Austríaco",
  bel: "Belga",
  sui: "Suíço",
  arg: "Argentino",
  nzl: "Neozelandês",
  rsa: "Sul-africano",
  rus: "Russo",
  pol: "Polonês",
  chn: "Chinês",
  usa: "Americano",
  idn: "Indonésio",
  irl: "Irlandês",
  col: "Colombiano",
  ven: "Venezuelano",
  ind: "Indiano",
  mas: "Malaio",
  hun: "Húngaro",
  cze: "Tcheco",
  svk: "Eslovaco",
  est: "Estoniano",
  lva: "Letão",
  ltu: "Lituano",
  are: "Emiradense",
  sau: "Saudita",
  bhr: "Barenita",
  tur: "Turco",
  gre: "Grego",
  rou: "Romeno",
  bul: "Búlgaro",
  cro: "Croata",
  srb: "Sérvio",
  svn: "Esloveno",
  nor: "Norueguês",
  isl: "Islandês",
  isr: "Israelense",
  egy: "Egípcio",
  mar: "Marroquino",
  chi: "Chileno",
  uru: "Uruguaio",
  par: "Paraguaio",
  per: "Peruano",
  ecu: "Equatoriano",
  bol: "Boliviano",
  kor: "Coreano",
  sgp: "Singapurense",
  hkg: "Hongkonguês",
  twn: "Taiwanês",
  phi: "Filipino",
  vnm: "Vietnamita",
  nga: "Nigeriano",
  ken: "Queniano",
  gha: "Ganês",
};

const COUNTRY_PT_BR: Record<string, string> = {
  "united kingdom": "Britânico",
  "great britain": "Britânico",
  england: "Inglês",
  netherlands: "Neerlandês",
  "the netherlands": "Neerlandês",
  "kingdom of the netherlands": "Neerlandês",
  thailand: "Tailandês",
  spain: "Espanhol",
  italy: "Italiano",
  france: "Francês",
  germany: "Alemão",
  australia: "Australiano",
  canada: "Canadense",
  portugal: "Português",
  brazil: "Brasileiro",
  mexico: "Mexicano",
  finland: "Finlandês",
  monaco: "Monegasco",
  japan: "Japonês",
  denmark: "Dinamarquês",
  sweden: "Sueco",
  austria: "Austríaco",
  belgium: "Belga",
  switzerland: "Suíço",
  argentina: "Argentino",
  "new zealand": "Neozelandês",
  "south africa": "Sul-africano",
  russia: "Russo",
  poland: "Polonês",
  china: "Chinês",
  "united states": "Americano",
  "united states of america": "Americano",
  indonesia: "Indonésio",
  ireland: "Irlandês",
  colombia: "Colombiano",
  venezuela: "Venezuelano",
  india: "Indiano",
  malaysia: "Malaio",
  hungary: "Húngaro",
  "czech republic": "Tcheco",
  czechia: "Tcheco",
  slovakia: "Eslovaco",
  estonia: "Estoniano",
  latvia: "Letão",
  lithuania: "Lituano",
  "united arab emirates": "Emiradense",
  "saudi arabia": "Saudita",
  bahrain: "Barenita",
  turkey: "Turco",
  greece: "Grego",
  romania: "Romeno",
  bulgaria: "Búlgaro",
  croatia: "Croata",
  serbia: "Sérvio",
  slovenia: "Esloveno",
  norway: "Norueguês",
  iceland: "Islandês",
  israel: "Israelense",
  egypt: "Egípcio",
  morocco: "Marroquino",
  chile: "Chileno",
  uruguay: "Uruguaio",
  paraguay: "Paraguaio",
  peru: "Peruano",
  ecuador: "Equatoriano",
  bolivia: "Boliviano",
  "south korea": "Sul-coreano",
  singapore: "Singapurense",
  "hong kong": "Hongkonguês",
  taiwan: "Taiwanês",
  philippines: "Filipino",
  vietnam: "Vietnamita",
  nigeria: "Nigeriano",
  kenya: "Queniano",
  ghana: "Ganês",
};

const PT_BR_FORMS: Record<string, string> = {
  "paises baixos": "Neerlandês",
  holanda: "Neerlandês",
  holandes: "Neerlandês",
  holandesa: "Neerlandês",
  brasil: "Brasileiro",
  brasileiro: "Brasileiro",
  brasileira: "Brasileiro",
  italia: "Italiano",
  italiano: "Italiano",
  italiana: "Italiano",
  franca: "Francês",
  frances: "Francês",
  francesa: "Francês",
  alemanha: "Alemão",
  alemao: "Alemão",
  alema: "Alemão",
  espanha: "Espanhol",
  espanhol: "Espanhol",
  espanhola: "Espanhol",
  "reino unido": "Britânico",
  britanico: "Britânico",
  britanica: "Britânico",
  mexico: "Mexicano",
  mexicano: "Mexicano",
  mexicana: "Mexicano",
  japao: "Japonês",
  japones: "Japonês",
  japonesa: "Japonês",
  monaco: "Monegasco",
  monegasco: "Monegasco",
  monegasca: "Monegasco",
  canada: "Canadense",
  canadense: "Canadense",
  australia: "Australiano",
  australiano: "Australiano",
  australiana: "Australiano",
  tailandia: "Tailandês",
  tailandes: "Tailandês",
  tailandesa: "Tailandês",
  portugal: "Português",
  portugues: "Português",
  portuguesa: "Português",
  suico: "Suíço",
  suica: "Suíço",
  belgica: "Belga",
  belga: "Belga",
  austria: "Austríaco",
  austriaco: "Austríaco",
  austriaca: "Austríaco",
  suecia: "Sueco",
  sueco: "Sueco",
  sueca: "Sueco",
  finlandia: "Finlandês",
  finlandes: "Finlandês",
  finlandesa: "Finlandês",
  dinamarca: "Dinamarquês",
  dinamarques: "Dinamarquês",
  dinamarquesa: "Dinamarquês",
  argentino: "Argentino",
  argentina: "Argentino",
  russia: "Russo",
  russo: "Russo",
  russa: "Russo",
  china: "Chinês",
  chines: "Chinês",
  chinesa: "Chinês",
  "estados unidos": "Americano",
  americano: "Americano",
  americana: "Americano",
  indonesia: "Indonésio",
  indonesio: "Indonésio",
  polonia: "Polonês",
  polones: "Polonês",
  polonesa: "Polonês",
  hungria: "Húngaro",
  hungaro: "Húngaro",
  hungara: "Húngaro",
  tcheco: "Tcheco",
  tcheca: "Tcheco",
  "nova zelandia": "Neozelandês",
  neozelandes: "Neozelandês",
  neozelandesa: "Neozelandês",
  "africa do sul": "Sul-africano",
  "sul africano": "Sul-africano",
  "coreia do sul": "Sul-coreano",
  irlanda: "Irlandês",
  irlandes: "Irlandês",
  irlandesa: "Irlandês",
  escocia: "Escocês",
  escoces: "Escocês",
  escocesa: "Escocês",
  inglaterra: "Inglês",
  ingles: "Inglês",
  inglesa: "Inglês",
  "pais de gales": "Galês",
  gales: "Galês",
  noruega: "Norueguês",
  noruegues: "Norueguês",
  norueguesa: "Norueguês",
  islandia: "Islandês",
  islandes: "Islandês",
  grecia: "Grego",
  grego: "Grego",
  grega: "Grego",
  turquia: "Turco",
  turco: "Turco",
  turca: "Turco",
  romenia: "Romeno",
  romeno: "Romeno",
  romena: "Romeno",
  bulgaria: "Búlgaro",
  bulgaro: "Búlgaro",
  bulgara: "Búlgaro",
  croacia: "Croata",
  croata: "Croata",
  servia: "Sérvio",
  servio: "Sérvio",
  eslovenia: "Esloveno",
  esloveno: "Esloveno",
  eslovena: "Esloveno",
  eslovaquia: "Eslovaco",
  eslovaco: "Eslovaco",
  eslovaca: "Eslovaco",
  estonia: "Estoniano",
  estoniano: "Estoniano",
  letonia: "Letão",
  letao: "Letão",
  lituania: "Lituano",
  lituano: "Lituano",
  "emirados arabes unidos": "Emiradense",
  emiradense: "Emiradense",
  "arabia saudita": "Saudita",
  saudita: "Saudita",
  bahrein: "Barenita",
  barein: "Barenita",
  barenita: "Barenita",
  marrocos: "Marroquino",
  marroquino: "Marroquino",
  marroquina: "Marroquino",
  chile: "Chileno",
  chileno: "Chileno",
  chilena: "Chileno",
  uruguai: "Uruguaio",
  uruguaio: "Uruguaio",
  uruguaia: "Uruguaio",
  paraguai: "Paraguaio",
  paraguaio: "Paraguaio",
  peru: "Peruano",
  peruano: "Peruano",
  peruana: "Peruano",
  equador: "Equatoriano",
  equatoriano: "Equatoriano",
  bolivia: "Boliviano",
  boliviano: "Boliviano",
  boliviana: "Boliviano",
  venezuela: "Venezuelano",
  venezuelano: "Venezuelano",
  venezuelana: "Venezuelano",
  colombia: "Colombiano",
  colombiano: "Colombiano",
  colombiana: "Colombiano",
  india: "Indiano",
  indiano: "Indiano",
  indiana: "Indiano",
  malasia: "Malaio",
  malaio: "Malaio",
  malaia: "Malaio",
  singapura: "Singapurense",
  singapurense: "Singapurense",
  coreano: "Coreano",
  coreana: "Coreano",
  vietnamita: "Vietnamita",
  filipino: "Filipino",
  filipina: "Filipino",
  nigeria: "Nigeriano",
  nigeriano: "Nigeriano",
  quenia: "Queniano",
  queniano: "Queniano",
  gana: "Ganês",
  ganes: "Ganês",
  egito: "Egípcio",
  egipcio: "Egípcio",
  israel: "Israelense",
  israelense: "Israelense",
  libano: "Libanês",
  libanes: "Libanês",
  kuwait: "Kuwaitiano",
  kuwaitiano: "Kuwaitiano",
  catar: "Catariano",
  catariano: "Catariano",
};

function normalize(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function resolveNationalityPtBr(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const trimmed = value.trim();
  if (trimmed.length === 0) return null;
  const key = normalize(trimmed);
  const direct = NATIONALITY_PT_BR[key] ?? COUNTRY_PT_BR[key] ?? PT_BR_FORMS[key];
  if (direct) return direct;
  if (trimmed.length === 3) {
    const code = NATIONALITY_PT_BR[trimmed.toLowerCase()];
    if (code) return code;
  }
  return trimmed;
}

export function feminizeNationalityPtBr(nationality: string): string {
  const trimmed = nationality.trim();
  if (trimmed.length === 0) return trimmed;
  const last = trimmed.slice(-1).toLowerCase();
  if (last === "a" || last === "e" || last === "i" || last === "u") return trimmed;
  if (trimmed.endsWith("ão")) return `${trimmed.slice(0, -2)}ã`;
  if (trimmed.endsWith("uês")) return `${trimmed.slice(0, -3)}uesa`;
  if (trimmed.endsWith("ês")) return `${trimmed.slice(0, -2)}esa`;
  if (trimmed.endsWith("ol")) return `${trimmed}a`;
  if (last === "o") return `${trimmed.slice(0, -1)}a`;
  return trimmed;
}
