const NATIONALITY_PT_BR: Record<string, string> = {
  british: "Britânico",
  english: "Inglês",
  scottish: "Escocês",
  welsh: "Galês",
  dutch: "Neerlandês",
  netherlandish: "Neerlandês",
  thai: "Tailandês",
  spanish: "Espanhol",
  italian: "Italiano",
  french: "Francês",
  german: "Alemão",
  australian: "Australiano",
  canadian: "Canadense",
  portuguese: "Português",
  brazilian: "Brasileiro",
  mexican: "Mexicano",
  finnish: "Finlandês",
  monegasque: "Monegasco",
  monégasque: "Monegasco",
  japanese: "Japonês",
  danish: "Dinamarquês",
  swedish: "Sueco",
  austrian: "Austríaco",
  belgian: "Belga",
  swiss: "Suíço",
  argentine: "Argentino",
  argentinian: "Argentino",
  "new zealander": "Neozelandês",
  "south african": "Sul-africano",
  russian: "Russo",
  polish: "Polonês",
  chinese: "Chinês",
  american: "Americano",
  indonesian: "Indonésio",
  irish: "Irlandês",
  colombian: "Colombiano",
  venezuelan: "Venezuelano",
  indian: "Indiano",
  malaysian: "Malaio",
  hungarian: "Húngaro",
  czech: "Tcheco",
  slovak: "Eslovaco",
  estonian: "Estoniano",
  latvian: "Letão",
  lithuanian: "Lituano",
  emirati: "Emiradense",
  saudi: "Saudita",
  bahraini: "Barenita",
  kuwaiti: "Kuwaitiano",
  qatari: "Catariano",
  turkish: "Turco",
  greek: "Grego",
  romanian: "Romeno",
  bulgarian: "Búlgaro",
  croatian: "Croata",
  serbian: "Sérvio",
  slovenian: "Esloveno",
  norwegian: "Norueguês",
  icelandic: "Islandês",
  israeli: "Israelense",
  lebanese: "Libanês",
  egyptian: "Egípcio",
  moroccan: "Marroquino",
  chilean: "Chileno",
  uruguayan: "Uruguaio",
  paraguayan: "Paraguaio",
  peruvian: "Peruano",
  ecuadorian: "Equatoriano",
  bolivian: "Boliviano",
  korean: "Coreano",
  "south korean": "Sul-coreano",
  singaporean: "Singapurense",
  "hong konger": "Hongkonguês",
  taiwanese: "Taiwanês",
  filipino: "Filipino",
  vietnamese: "Vietnamita",
  nigerian: "Nigeriano",
  kenyan: "Queniano",
  ghanaian: "Ganês",

  gbr: "Britânico",
  ned: "Neerlandês",
  tha: "Tailandês",
  esp: "Espanhol",
  ita: "Italiano",
  fra: "Francês",
  ger: "Alemão",
  deu: "Alemão",
  aus: "Australiano",
  can: "Canadense",
  por: "Português",
  bra: "Brasileiro",
  mex: "Mexicano",
  fin: "Finlandês",
  mon: "Monegasco",
  jpn: "Japonês",
  den: "Dinamarquês",
  swe: "Sueco",
  aut: "Austríaco",
  bel: "Belga",
  sui: "Suíço",
  arg: "Argentino",
  nzl: "Neozelandês",
  rsa: "Sul-africano",
  rus: "Russo",
  pol: "Polonês",
  chn: "Chinês",
  usa: "Americano",
  idn: "Indonésio",
  irl: "Irlandês",
  col: "Colombiano",
  ven: "Venezuelano",
  ind: "Indiano",
  mas: "Malaio",
  hun: "Húngaro",
  cze: "Tcheco",
  svk: "Eslovaco",
  est: "Estoniano",
  lva: "Letão",
  ltu: "Lituano",
  are: "Emiradense",
  sau: "Saudita",
  bhr: "Barenita",
  tur: "Turco",
  gre: "Grego",
  rou: "Romeno",
  bul: "Búlgaro",
  cro: "Croata",
  srb: "Sérvio",
  svn: "Esloveno",
  nor: "Norueguês",
  isl: "Islandês",
  isr: "Israelense",
  egy: "Egípcio",
  mar: "Marroquino",
  chi: "Chileno",
  uru: "Uruguaio",
  par: "Paraguaio",
  per: "Peruano",
  ecu: "Equatoriano",
  bol: "Boliviano",
  kor: "Coreano",
  sgp: "Singapurense",
  hkg: "Hongkonguês",
  twn: "Taiwanês",
  phi: "Filipino",
  vnm: "Vietnamita",
  nga: "Nigeriano",
  ken: "Queniano",
  gha: "Ganês",
};

const COUNTRY_PT_BR: Record<string, string> = {
  "united kingdom": "Britânico",
  "great britain": "Britânico",
  england: "Inglês",
  netherlands: "Neerlandês",
  "the netherlands": "Neerlandês",
  thailand: "Tailandês",
  spain: "Espanhol",
  italy: "Italiano",
  france: "Francês",
  germany: "Alemão",
  australia: "Australiano",
  canada: "Canadense",
  portugal: "Português",
  brazil: "Brasileiro",
  mexico: "Mexicano",
  finland: "Finlandês",
  monaco: "Monegasco",
  japan: "Japonês",
  denmark: "Dinamarquês",
  sweden: "Sueco",
  austria: "Austríaco",
  belgium: "Belga",
  switzerland: "Suíço",
  argentina: "Argentino",
  "new zealand": "Neozelandês",
  "south africa": "Sul-africano",
  russia: "Russo",
  poland: "Polonês",
  china: "Chinês",
  "united states": "Americano",
  "united states of america": "Americano",
  indonesia: "Indonésio",
  ireland: "Irlandês",
  colombia: "Colombiano",
  venezuela: "Venezuelano",
  india: "Indiano",
  malaysia: "Malaio",
  hungary: "Húngaro",
  "czech republic": "Tcheco",
  czechia: "Tcheco",
  slovakia: "Eslovaco",
  estonia: "Estoniano",
  latvia: "Letão",
  lithuania: "Lituano",
  "united arab emirates": "Emiradense",
  "saudi arabia": "Saudita",
  bahrain: "Barenita",
  turkey: "Turco",
  greece: "Grego",
  romania: "Romeno",
  bulgaria: "Búlgaro",
  croatia: "Croata",
  serbia: "Sérvio",
  slovenia: "Esloveno",
  norway: "Norueguês",
  iceland: "Islandês",
  israel: "Israelense",
  egypt: "Egípcio",
  morocco: "Marroquino",
  chile: "Chileno",
  uruguay: "Uruguaio",
  paraguay: "Paraguaio",
  peru: "Peruano",
  ecuador: "Equatoriano",
  bolivia: "Boliviano",
  "south korea": "Sul-coreano",
  singapore: "Singapurense",
  "hong kong": "Hongkonguês",
  taiwan: "Taiwanês",
  philippines: "Filipino",
  vietnam: "Vietnamita",
  nigeria: "Nigeriano",
  kenya: "Queniano",
  ghana: "Ganês",
};

const COUNTRY_NAMES_PT_BR: Record<string, string> = {
  brazil: "Brasil",
  italy: "Itália",
  "united kingdom": "Reino Unido",
  "great britain": "Reino Unido",
  england: "Inglaterra",
  scotland: "Escócia",
  wales: "País de Gales",
  netherlands: "Países Baixos",
  "the netherlands": "Países Baixos",
  spain: "Espanha",
  france: "França",
  germany: "Alemanha",
  monaco: "Mônaco",
  belgium: "Bélgica",
  austria: "Áustria",
  switzerland: "Suíça",
  portugal: "Portugal",
  mexico: "México",
  canada: "Canadá",
  "united states": "Estados Unidos",
  "united states of america": "Estados Unidos",
  australia: "Austrália",
  "new zealand": "Nova Zelândia",
  japan: "Japão",
  china: "China",
  singapore: "Singapura",
  malaysia: "Malásia",
  thailand: "Tailândia",
  indonesia: "Indonésia",
  india: "Índia",
  "south korea": "Coreia do Sul",
  korea: "Coreia",
  russia: "Rússia",
  poland: "Polônia",
  hungary: "Hungria",
  "czech republic": "República Tcheca",
  czechia: "Tchéquia",
  slovakia: "Eslováquia",
  slovenia: "Eslovênia",
  croatia: "Croácia",
  serbia: "Sérvia",
  bulgaria: "Bulgária",
  romania: "Romênia",
  greece: "Grécia",
  turkey: "Turquia",
  finland: "Finlândia",
  sweden: "Suécia",
  norway: "Noruega",
  denmark: "Dinamarca",
  iceland: "Islândia",
  ireland: "Irlanda",
  "south africa": "África do Sul",
  argentina: "Argentina",
  chile: "Chile",
  colombia: "Colômbia",
  venezuela: "Venezuela",
  uruguay: "Uruguai",
  paraguay: "Paraguai",
  peru: "Peru",
  ecuador: "Equador",
  bolivia: "Bolívia",
  "saudi arabia": "Arábia Saudita",
  "united arab emirates": "Emirados Árabes Unidos",
  bahrain: "Bahrein",
  qatar: "Catar",
  kuwait: "Kuwait",
  azerbaijan: "Azerbaijão",
  georgia: "Geórgia",
  vietnam: "Vietnã",
  philippines: "Filipinas",
  taiwan: "Taiwan",
  "hong kong": "Hong Kong",
  israel: "Israel",
  egypt: "Egito",
  morocco: "Marrocos",
  nigeria: "Nigéria",
  kenya: "Quênia",
  ghana: "Gana",
  ethiopia: "Etiópia",
  tunisia: "Tunísia",
  algeria: "Argélia",
  ukraine: "Ucrânia",
  belarus: "Bielorrússia",
  kazakhstan: "Cazaquistão",
  uzbekistan: "Uzbequistão",
  pakistan: "Paquistão",
  bangladesh: "Bangladesh",
  "sri lanka": "Sri Lanka",
  nepal: "Nepal",
  myanmar: "Mianmar",
  cambodia: "Camboja",
  laos: "Laos",
  mongolia: "Mongólia",
};

const COUNTRY_ISO_PT_BR: Record<string, string> = {
  bra: "Brasil",
  ita: "Itália",
  gbr: "Reino Unido",
  ned: "Países Baixos",
  esp: "Espanha",
  fra: "França",
  ger: "Alemanha",
  deu: "Alemanha",
  mco: "Mônaco",
  bel: "Bélgica",
  aut: "Áustria",
  sui: "Suíça",
  por: "Portugal",
  mex: "México",
  can: "Canadá",
  usa: "Estados Unidos",
  aus: "Austrália",
  nzl: "Nova Zelândia",
  jpn: "Japão",
  chn: "China",
  sgp: "Singapura",
  mas: "Malásia",
  tha: "Tailândia",
  idn: "Indonésia",
  ind: "Índia",
  kor: "Coreia do Sul",
  rus: "Rússia",
  pol: "Polônia",
  hun: "Hungria",
  cze: "República Tcheca",
  svk: "Eslováquia",
  svn: "Eslovênia",
  cro: "Croácia",
  srb: "Sérvia",
  bul: "Bulgária",
  rou: "Romênia",
  gre: "Grécia",
  tur: "Turquia",
  fin: "Finlândia",
  swe: "Suécia",
  nor: "Noruega",
  den: "Dinamarca",
  isl: "Islândia",
  irl: "Irlanda",
  rsa: "África do Sul",
  arg: "Argentina",
  chi: "Chile",
  col: "Colômbia",
  ven: "Venezuela",
  uru: "Uruguai",
  par: "Paraguai",
  per: "Peru",
  ecu: "Equador",
  bol: "Bolívia",
  sau: "Arábia Saudita",
  are: "Emirados Árabes Unidos",
  bhr: "Bahrein",
  qat: "Catar",
  kuw: "Kuwait",
  aze: "Azerbaijão",
};

function normalize(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function localizeNationalityPtBr(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const trimmed = value.trim();
  if (trimmed.length === 0) return null;
  const key = normalize(trimmed);
  return NATIONALITY_PT_BR[key] ?? COUNTRY_PT_BR[key] ?? trimmed;
}

export function localizeCountryPtBr(value: string | null | undefined): string | null {
  if (value === null || value === undefined) return null;
  const trimmed = value.trim();
  if (trimmed.length === 0) return null;
  const key = normalize(trimmed);
  const direct = COUNTRY_NAMES_PT_BR[key] ?? COUNTRY_ISO_PT_BR[key];
  if (direct) return direct;
  if (trimmed.length === 3 && COUNTRY_ISO_PT_BR[trimmed.toLowerCase()]) {
    return COUNTRY_ISO_PT_BR[trimmed.toLowerCase()] as string;
  }
  return trimmed;
}
